### ISSUE TITLE
does not scrollback to first tab

### ISSUE THREAD

**Issue by jtadiarca** [yanzm/MaterialTabHost#2]
I have 4 tabs in my activity and here's the scenario:
1. From the first tab, scroll all the way to the last/4th tab.
2. Click the first tab indicator.

Expectes results:
- Scrolls back to first tab
  Actual results:
  -Nothing happens. Does not scroll back to first tab
  -This only happens to the first tab. Other tabs(2nd & 3rd) work fine.

**Comment by yanzm** [comment]
https://github.com/yanzm/MaterialTabHost/pull/1

**Comment by veersamrat** [comment]
**I found solution.**

```
tabHost.setOnTabChangedListener(new TabHost.OnTabChangeListener() {

            @Override
            public void onTabChanged(String tabId) {
                             viewPager.setCurrentItem(tabHost.getCurrentTab());
            }
        });
```
